spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cool?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: xltys1995
  mvc:
    static-path-pattern: /**
    view:
      prefix: view/
      suffix: .html

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml