server:
  port: 80

spring:
  datasource:
    # mysql
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/cool?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: xltys1995
    # sql-server
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.3.211:1433;databasename=cool
    username: sa
    password: sa@123
  mvc:
    static-path-pattern: /**
  redis:
    host: localhost
    port: 6379
    database: 0
#    password: xltys1995

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    field-strategy: 0

logging:
  path: /stock/out/logs

super:
  pwd: xltys1995

swagger:
  enable: true